# Correct configuration
name: Manual Workflow
on:
  workflow_dispatch:  # This enables manual triggering

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run task
        run: echo "Hello World"
